CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'halulu_api') THEN
        CREATE SCHEMA halulu_api;
    END IF;
END $EF$;

CREATE TABLE halulu_api.master_category (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Icon" character varying(255),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_master_category" PRIMARY KEY ("Id")
);

CREATE TABLE halulu_api.users (
    "Id" uuid NOT NULL,
    "FullName" character varying(255) NOT NULL,
    "Email" character varying(255) NOT NULL,
    "PhoneNumber" character varying(20) NOT NULL,
    "ProfileImage" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "LastLoginAt" timestamp with time zone,
    CONSTRAINT "PK_users" PRIMARY KEY ("Id")
);

CREATE TABLE halulu_api.master_subcategory (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "Icon" character varying(255),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CategoryId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_master_subcategory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_master_subcategory_master_category_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES halulu_api.master_category ("Id") ON DELETE CASCADE
);

CREATE TABLE halulu_api."OtpRecords" (
    "Id" uuid NOT NULL,
    "Email" character varying(255) NOT NULL,
    "OtpCode" character varying(10) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    "UsedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "AttemptCount" integer NOT NULL,
    "MaxAttempts" integer NOT NULL,
    "IsLocked" boolean NOT NULL,
    "UserId" uuid,
    "Purpose" integer NOT NULL,
    CONSTRAINT "PK_OtpRecords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OtpRecords_users_UserId" FOREIGN KEY ("UserId") REFERENCES halulu_api.users ("Id") ON DELETE SET NULL
);

CREATE TABLE halulu_api.providers (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "ServiceCategories" text,
    "ExperienceYears" integer NOT NULL DEFAULT 0,
    "Bio" character varying(1000),
    "ServiceAreas" text,
    "PricingModel" character varying(100),
    "Documents" text,
    "AvailabilitySlots" text,
    "Rating" numeric(3,2) NOT NULL DEFAULT 0.0,
    "Earnings" numeric(18,2) NOT NULL DEFAULT 0.0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_providers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_providers_users_UserId" FOREIGN KEY ("UserId") REFERENCES halulu_api.users ("Id") ON DELETE CASCADE
);

CREATE TABLE halulu_api.requesters (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Address" character varying(500),
    "PreferredCategories" text,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_requesters" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_requesters_users_UserId" FOREIGN KEY ("UserId") REFERENCES halulu_api.users ("Id") ON DELETE CASCADE
);

CREATE TABLE halulu_api.service_requests (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "BookingType" text NOT NULL,
    "MainCategory" character varying(100) NOT NULL,
    "SubCategory" character varying(100) NOT NULL,
    "Date" timestamp with time zone,
    "Time" character varying(20),
    "Location" character varying(500) NOT NULL,
    "Notes" character varying(1000),
    "AdditionalNotes" character varying(500),
    "Status" text NOT NULL DEFAULT 'Pending',
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_service_requests" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_service_requests_users_UserId" FOREIGN KEY ("UserId") REFERENCES halulu_api.users ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_master_category_IsActive" ON halulu_api.master_category ("IsActive");

CREATE UNIQUE INDEX "IX_master_category_Name" ON halulu_api.master_category ("Name");

CREATE UNIQUE INDEX "IX_master_subcategory_CategoryId_Name" ON halulu_api.master_subcategory ("CategoryId", "Name");

CREATE INDEX "IX_master_subcategory_IsActive" ON halulu_api.master_subcategory ("IsActive");

CREATE INDEX "IX_OtpRecords_Email_CreatedAt" ON halulu_api."OtpRecords" ("Email", "CreatedAt");

CREATE INDEX "IX_OtpRecords_UserId" ON halulu_api."OtpRecords" ("UserId");

CREATE INDEX "IX_providers_IsActive" ON halulu_api.providers ("IsActive");

CREATE INDEX "IX_providers_Rating" ON halulu_api.providers ("Rating");

CREATE UNIQUE INDEX "IX_providers_UserId" ON halulu_api.providers ("UserId");

CREATE INDEX "IX_requesters_IsActive" ON halulu_api.requesters ("IsActive");

CREATE UNIQUE INDEX "IX_requesters_UserId" ON halulu_api.requesters ("UserId");

CREATE INDEX "IX_service_requests_BookingType" ON halulu_api.service_requests ("BookingType");

CREATE INDEX "IX_service_requests_CreatedAt" ON halulu_api.service_requests ("CreatedAt");

CREATE INDEX "IX_service_requests_Status" ON halulu_api.service_requests ("Status");

CREATE INDEX "IX_service_requests_UserId" ON halulu_api.service_requests ("UserId");

CREATE INDEX "IX_service_requests_UserId_Status" ON halulu_api.service_requests ("UserId", "Status");

CREATE UNIQUE INDEX "IX_users_Email" ON halulu_api.users ("Email");

CREATE UNIQUE INDEX "IX_users_PhoneNumber" ON halulu_api.users ("PhoneNumber") WHERE "PhoneNumber" IS NOT NULL AND "PhoneNumber" != '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251101185138_InitialCreate', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE halulu_api.users ADD "Address" character varying(500);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251103054020_AddAddressToUser', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE halulu_api.users ADD "IsEmailVerified" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE halulu_api.users ADD "IsPhoneVerified" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251103054446_AddEmailPhoneVerificationFlags', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251103171138_FixServiceRequestRelationship', '8.0.0');

COMMIT;

START TRANSACTION;


                DO $$ 
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.table_constraints 
                              WHERE constraint_name = 'FK_service_requests_users_UserId1' 
                              AND table_schema = 'halulu_api') THEN
                        ALTER TABLE halulu_api.service_requests DROP CONSTRAINT "FK_service_requests_users_UserId1";
                    END IF;
                END $$;
            


                DO $$ 
                BEGIN
                    IF EXISTS (SELECT 1 FROM pg_indexes 
                              WHERE indexname = 'IX_service_requests_UserId1' 
                              AND schemaname = 'halulu_api') THEN
                        DROP INDEX halulu_api."IX_service_requests_UserId1";
                    END IF;
                END $$;
            


                DO $$ 
                BEGIN
                    IF EXISTS (SELECT 1 FROM information_schema.columns 
                              WHERE table_name = 'service_requests' 
                              AND column_name = 'UserId1' 
                              AND table_schema = 'halulu_api') THEN
                        ALTER TABLE halulu_api.service_requests DROP COLUMN "UserId1";
                    END IF;
                END $$;
            

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251104083716_UpdateServiceRequestToUseRequesterId', '8.0.0');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251104083956_RenameUserIdToRequesterId', '8.0.0');

COMMIT;

